-- These commands create the required database for our Dog Walker app

-- drop database if it exits
drop database dogwalker;


-- create the database;
create database dogwalker;

-- connect to the database. Note: you need to on the cli psql
\c dogwalker;

-- now create the main tables.

CREATE table credentials (
    credential_id SERIAL PRIMARY KEY NOT NULL,
    credential_email VARCHAR(20) NOT NULL,
    credential_password VARCHAR(20) NOT NULL,
    credential_type VARCHAR(1) NOT NULL
);

INSERT INTO credentials (credential_email, credential_password, credential_type) VALUES ('ared','zzz123','o');
INSERT INTO credentials (credential_email, credential_password, credential_type) VALUES ('ppiper','zzz124','o');
INSERT INTO credentials (credential_email, credential_password, credential_type) VALUES ('rgoodwin','zzz125','o');
INSERT INTO credentials (credential_email, credential_password, credential_type) VALUES ('vpham','zzz123','w');
INSERT INTO credentials (credential_email, credential_password, credential_type) VALUES ('cmcullochr','zzz124','w');
INSERT INTO credentials (credential_email, credential_password, credential_type) VALUES ('bbaustia','zzz125','w');

-- create the services
CREATE TABLE services (
    service_id SERIAL PRIMARY KEY NOT NULL,
    service_type VARCHAR(4) NOT NULL,
    service_fee NUMERIC(4,2) NOT NULL
);

-- SERVICES DATA
insert into services (service_type, service_fee) VALUES ('na', 0);
insert into services (service_type, service_fee) VALUES ('30WO', 25);
insert into services (service_type, service_fee) VALUES ('60WO', 40);
insert into services (service_type, service_fee) VALUES ('30HV', 20);
insert into services (service_type, service_fee) VALUES ('60HV', 35);

-- CREATE TABLE OWNERS
CREATE TABLE owners (
owner_id SERIAL PRIMARY KEY NOT NULL,
owner_firstname VARCHAR(20) NOT NULL,
owner_lastname VARCHAR(20) NOT NULL,
owner_street_address VARCHAR(50) NOT NULL,
owner_town VARCHAR(50) NOT NULL,
owner_postcode INTEGER NOT NULL,
owner_mobile VARCHAR(10) NOT NULL,
owner_email VARCHAR(20) NOT NULL,
owner_dob DATE NOT NULL,
owner_licence_photo VARCHAR(100),
owner_overall_rating NUMERIC,
owner_active_membership BOOLEAN DEFAULT TRUE,
UNIQUE (owner_email),
UNIQUE (owner_mobile)
);


-- OWNERS DATA
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('andre','reid','11 Playne Street','Frankston',3199,'0401000000','ar@areid.com','2000-01-01','notapplied','1','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('paddy','piper','11 Austin Road','Seaford',3198,'0401000001','pp@ppiper.com','2000-01-02','notapplied','2','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('riccardo','goodwin','11 Walkers Road','Carrum',3197,'0401000002','rg@rgoodwin.com','2000-01-03','notapplied','3','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('anushka','jacobson','11 York Street','Mornington',3931,'0401000003','aj@ajacobson.com','2000-01-04','notapplied','4','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('carlton','mora','11 Walkers Road','Mt Eliza',3930,'0401000004','cm@cmora.com','2000-01-05','notapplied','5','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('juliet','morrison','11 Clarendon Street','Thornbury',3071,'0401000005','jm@jmorrison.com','2000-01-06','notapplied','1','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('mckenzie','wheatley','11 Cheddar Road','Reservoir',3073,'0401000006','mw@mwheatley.com','2000-01-07','notapplied','2','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('shuaib','blaese','11 The Blvd','Thomastown',3074,'0401000007','sb@sblaese.com','2000-01-08','notapplied','3','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('portia','jennings','11 Oherns Road','Epping',3076,'0401000008','pj@pjennings.com','2000-01-09','notapplied','4','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('pearl','mohamed','11 Bitburg Street','Jacana',3047,'0401000009','pm@pmohamed.com','2000-01-10','notapplied','5','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('santino','sharpe','12 Playne Street','Frankston',3199,'0401000010','ss@ssharpe.com','2000-01-11','notapplied','1','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('adnaan','truong','12 Austin Road','Seaford',3198,'0401000011','at@atruong.com','2000-01-12','notapplied','2','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('natalia','massey','12 Walkers Road','Carrum',3197,'0401000012','nm@nmassey.com','2000-01-13','notapplied','3','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('zayd','hook','12 York Street','Mornington',3931,'0401000013','zh@zhook.com','2000-01-14','notapplied','4','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('thomas','ramirez','12 Walkers Road','Mt Eliza',3930,'0401000014','tr@tramirez.com','2008-01-03','notapplied','5','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('mikolaj','fischer','12 Clarendon Street','Thornbury',3071,'0401000015','mf@mfischer.com','2014-01-04','notapplied','1','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('mila','hewitt','12 Cheddar Road','Reservoir',3073,'0401000016','mh@mhewitt.com','2012-01-05','notapplied','2','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('marian','talley','12 The Blvd','Thomastown',3074,'0401000017','mt@mtalley.com','2000-01-18','notapplied','3','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('alma','peralta','12 Oherns Road','Epping',3076,'0401000018','ap@aperalta.com','2000-01-19','notapplied','4','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('kacie','wilder','12 Bitburg Street','Jacana',3047,'0401000019','kw@kwilder.com','2000-01-01','notapplied','5','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('kymani','leonard','13 Playne Street','Frankston',3199,'0401000020','kl@kleonard.com','2000-01-02','notapplied','1','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('charis','rangel','13 Austin Road','Seaford',3198,'0401000021','cr@crangel.com','2000-01-03','notapplied','2','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('rupert','copeland','13 Walkers Road','Carrum',3197,'0401000022','rc@rcopeland.com','2000-01-04','notapplied','3','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('keyan','dickinson','13 York Street','Mornington',3931,'0401000023','kd@kdickinson.com','2000-01-05','notapplied','4','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('liyah','norton','13 Walkers Road','Mt Eliza',3930,'0401000024','ln@lnorton.com','2000-01-06','notapplied','5','FALSE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('sammy','mellor','13 Clarendon Street','Thornbury',3071,'0401000025','sm@smellor.com','2000-01-07','notapplied','1','FALSE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('dwayne','cottrell','13 Cheddar Road','Reservoir',3073,'0401000026','dc@dcottrell.com','2000-01-08','notapplied','2','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('brooke','sawyer','13 The Blvd','Thomastown',3074,'0401000027','bs@bsawyer.com','2000-01-09','notapplied','3','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('emilio','mustafa','13 Oherns Road','Epping',3076,'0401000028','em@emustafa.com','2000-01-10','notapplied','4','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('aroush','martin','13 Bitburg Street','Jacana',3047,'0401000029','am@amartin.com','2000-01-11','notapplied','5','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('gordon','thornton','13 Playne Street','Frankston',3199,'0401000030','gt@gthornton.com','2000-01-12','notapplied','1','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('ayub','denton','14 Austin Road','Seaford',3198,'0401000031','ad@adenton.com','2000-01-13','notapplied','2','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('vlad','mayer','14 Walkers Road','Carrum',3197,'0401000032','vm@vmayer.com','2000-01-14','notapplied','3','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('arif','kelly','14 York Street','Mornington',3931,'0401000033','ak@akelly.com','2008-01-03','notapplied','4','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('ceara','mcfarland','14 Walkers Road','Mt Eliza',3930,'0401000034','cm@cmcfarland.com','2014-01-04','notapplied','5','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('chris','mcphee','14 Clarendon Street','Thornbury',3071,'0401000035','cm@cmcphee.com','2012-01-05','notapplied','1','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('gurpreet','cowan','14 Cheddar Road','Reservoir',3073,'0401000036','gc@gcowan.com','2000-01-18','notapplied','2','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('aaliya','henry','14 The Blvd','Thomastown',3074,'0401000037','ah@ahenry.com','2000-01-19','notapplied','3','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('becky','hayden','14 Oherns Road','Epping',3076,'0401000038','bh@bhayden.com','2000-01-01','notapplied','4','TRUE');
insert into owners (owner_firstname, owner_lastname, owner_street_address, owner_town, owner_postcode, owner_mobile, owner_email, owner_dob,owner_licence_photo, owner_overall_rating, owner_active_membership) VALUES ('lili','byers','14 Bitburg Street','Jacana',3047,'0401000039','lb@lbyers.com','2000-01-02','notapplied','5','TRUE');




-- THIS TABLE CREATE DOGS
CREATE TABLE dogs (
dog_id SERIAL PRIMARY KEY NOT NULL,
dog_firstname VARCHAR(20) NOT NULL,
dog_photo VARCHAR(100) NOT NULL,
dog_breed VARCHAR(20) NOT NULL,
dog_size VARCHAR(1) NOT NULL,
dog_always_leashed BOOLEAN DEFAULT TRUE,
owner_id INTEGER,
FOREIGN KEY (owner_id) REFERENCES owners(owner_id)
);


-- DOGS DATA

INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('fido','notapplied','sausage','S','TRUE',1);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('charlie','notapplied','alsatian','L','TRUE',2);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('mick','notapplied','mutt','M','FALSE',3);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('jess','notapplied','collie','M','TRUE',4);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('jessie','notapplied','lapdog','S','FALSE',5);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('tito','notapplied','retreiver','L','TRUE',6);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('brutus','notapplied','labrador','L','TRUE',7);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('jen','notapplied','pug','S','FALSE',8);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('tomtom','notapplied','corgi','S','FALSE',9);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('daisy','notapplied','terrier','S','FALSE',10);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Loki','notapplied','sausage','S','FALSE',11);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Toki','notapplied','alsatian','L','TRUE',12);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Miko','notapplied','mutt','M','FALSE',13);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Joki','notapplied','collie','M','TRUE',14);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Noki','notapplied','lapdog','S','TRUE',15);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Roki','notapplied','retreiver','L','TRUE',16);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Zoki','notapplied','labrador','L','FALSE',17);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Woki','notapplied','pug','S','TRUE',18);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Poki','notapplied','corgi','S','FALSE',19);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Soki','notapplied','terrier','S','TRUE',20);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('fido','notapplied','sausage','S','TRUE',21);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('charlie','notapplied','alsatian','L','FALSE',22);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('mick','notapplied','mutt','M','TRUE',23);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('jess','notapplied','collie','M','TRUE',24);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('jessie','notapplied','lapdog','S','FALSE',25);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('tito','notapplied','retreiver','L','TRUE',26);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('brutus','notapplied','labrador','L','FALSE',27);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('jen','notapplied','pug','S','TRUE',28);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('tomtom','notapplied','corgi','S','TRUE',29);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('daisy','notapplied','terrier','S','FALSE',30);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Loki','notapplied','sausage','S','TRUE',31);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Toki','notapplied','alsatian','L','FALSE',32);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Miko','notapplied','mutt','M','TRUE',33);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Joki','notapplied','collie','M','TRUE',34);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Noki','notapplied','lapdog','S','FALSE',35);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Roki','notapplied','retreiver','L','FALSE',36);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Zoki','notapplied','labrador','L','FALSE',37);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Woki','notapplied','pug','S','FALSE',38);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Poki','notapplied','corgi','S','TRUE',39);
INSERT INTO DOGS (dog_firstname, dog_photo, dog_breed, dog_size, dog_always_leashed, owner_id) VALUES  ('Soki','notapplied','terrier','S','FALSE',40);
SELECT count(*) FROM dogs;




-- THIS TABLE CREATES THE WALKERS TABLE
CREATE TABLE walkers (
    walker_id SERIAL PRIMARY KEY NOT NULL,
    walker_firstname VARCHAR(20) NOT NULL,
    walker_lastname VARCHAR(20) NOT NULL,
    walker_street_address VARCHAR(50) NOT NULL,
    walker_town VARCHAR(50) NOT NULL,
    walker_postcode INTEGER NOT NULL,
    walker_mobile VARCHAR(10) NOT NULL,
    walker_email VARCHAR(20)  NOT NULL,
    walker_dob DATE NOT NULL,
    walker_licence_photo VARCHAR(100),
    walker_overall_rating NUMERIC,
    walker_dog_size_preference VARCHAR(1) NOT NULL,
    walker_30WO INTEGER,
    walker_60WO INTEGER,
    walker_30HV INTEGER,
    walker_60HV INTEGER,
    walker_active_membership BOOLEAN DEFAULT TRUE,
    UNIQUE (walker_email),
    UNIQUE (walker_mobile)
);


-- WALKER dATA
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('vivaan','pham','1 Playne Street','Frankston',3199,'0400000000','vp@vpham.com','2000-01-01','notapplied',1,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('charis','mcculloch','1 Austin Road','Seaford',3198,'0400000001','cm@cmcculloch.com','2000-01-02','notapplied',2,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('brooklyn','bautista','1 Walkers Road','Carrum',3197,'0400000002','bb@bbautista.com','2000-01-03','notapplied',3,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('dominique','avalos','1 York Street','Mornington',3931,'0400000003','da@davalos.com','2000-01-04','notapplied',4,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('charity','black','1 Walkers Road','Mt Eliza',3930,'0400000004','cb@cblack.com','2000-01-05','notapplied',5,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('murtaza','kumar','1 Clarendon Street','Thornbury',3071,'0400000005','mk@mkumar.com','2000-01-06','notapplied',1,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('kaison','holmes','1 Cheddar Road','Reservoir',3073,'0400000006','kh@kholmes.com','2000-01-07','notapplied',2,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('arielle','solomon','1 The Blvd','Thomastown',3074,'0400000007','as@asolomon.com','2000-01-08','notapplied',3,'A',1,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('cathal','east','1 Oherns Road','Epping',3076,'0400000008','ce@ceast.com','2000-01-09','notapplied',4,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('aairah','randolph','1 Bitburg Street','Jacana',3047,'0400000009','ar@arandolph.com','2000-01-10','notapplied',5,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('millie','kirby','2 Playne Street','Frankston',3199,'0400000010','mk@mkirby.com','2000-01-11','notapplied',1,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('armaan','galindo','2 Austin Road','Seaford',3198,'0400000011','ag@agalindo.com','2000-01-12','notapplied',2,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('haroon','ponce','2 Walkers Road','Carrum',3197,'0400000012','hp@hponce.com','2000-01-13','notapplied',3,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('aneesa','durham','2 York Street','Mornington',3931,'0400000013','ad@adurham.com','2000-01-14','notapplied',4,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('jeanette','byrne','2 Walkers Road','Mt Eliza',3930,'0400000014','jb@jbyrne.com','2008-01-01','notapplied',5,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('stefanie','riley','2 Clarendon Street','Thornbury',3071,'0400000015','sr@sriley.com','2012-01-02','notapplied',1,'A',1,0,0,0,'FALSE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('dean','myers','2 Cheddar Road','Reservoir',3073,'0400000016','dm@dmyers.com','2009-01-03','notapplied',2,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('nicole','cortes','2 The Blvd','Thomastown',3074,'0400000017','nc@ncortes.com','2000-01-18','notapplied',3,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('braydon','singh','2 Oherns Road','Epping',3076,'0400000018','bs@bsingh.com','2000-01-19','notapplied',4,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('skylah','hassan','2 Bitburg Street','Jacana',3047,'0400000019','sh@shassan.com','2000-01-01','notapplied',5,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('nolan','bains','3 Playne Street','Frankston',3199,'0400000020','nb@nbains.com','2000-01-02','notapplied',1,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('harleen','pratt','3 Austin Road','Seaford',3198,'0400000021','hp@hpratt.com','2000-01-03','notapplied',2,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('marianna','whitley','3 Walkers Road','Carrum',3197,'0400000022','mw@mwhitley.com','2000-01-04','notapplied',3,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('colm','dunlap','3 York Street','Mornington',3931,'0400000023','cd@cdunlap.com','2000-01-05','notapplied',4,'A',1,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('aleyna','howells','3 Walkers Road','Mt Eliza',3930,'0400000024','ah@ahowells.com','2000-01-06','notapplied',5,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('uwais','dalton','3 Clarendon Street','Thornbury',3071,'0400000025','ud@udalton.com','2000-01-07','notapplied',1,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('cherry','gilliam','3 Cheddar Road','Reservoir',3073,'0400000026','cg@cgilliam.com','2000-01-08','notapplied',2,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('chloe','cochran','3 The Blvd','Thomastown',3074,'0400000027','cc@ccochran.com','2000-01-09','notapplied',3,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('suzanna','bridges','3 Oherns Road','Epping',3076,'0400000028','sb@sbridges.com','2000-01-10','notapplied',4,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('kaitlan','calhoun','3 Bitburg Street','Jacana',3047,'0400000029','kc@kcalhoun.com','2000-01-11','notapplied',5,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('lance','christensen','4 Playne Street','Frankston',3199,'0400000030','lc@lchristensen.com','2000-01-12','notapplied',1,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('zion','gunn','4 Austin Road','Seaford',3198,'0400000031','zg@zgunn.com','2000-01-13','notapplied',2,'A',1,0,0,0,'FALSE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('amandeep','hodge','4 Walkers Road','Carrum',3197,'0400000032','ah@ahodge.com','2000-01-14','notapplied',3,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('rhydian','valentine','4 York Street','Mornington',3931,'0400000033','rv@rvalentine.com','2008-01-01','notapplied',4,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('arandeep','gomez','4 Walkers Road','Mt Eliza',3930,'0400000034','ag@agomez.com','2012-01-02','notapplied',5,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('siya','santos','4 Clarendon Street','Thornbury',3071,'0400000035','ss@ssantos.com','2009-01-03','notapplied',1,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('tyreke','drake','4 Cheddar Road','Reservoir',3073,'0400000036','td@tdrake.com','2000-01-18','notapplied',2,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('diane','dillon','4 The Blvd','Thomastown',3074,'0400000037','dd@ddillon.com','2000-01-19','notapplied',3,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('mathew','baldwin','4 Oherns Road','Epping',3076,'0400000038','mb@mbaldwin.com','2000-01-01','notapplied',4,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('rhiannon','bryant','4 Bitburg Street','Jacana',3047,'0400000039','rb@rbryant.com','2000-01-02','notapplied',5,'A',1,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('markus','cope','5 Playne Street','Frankston',3199,'0400000040','mc@mcope.com','2000-01-03','notapplied',1,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('ziva','alford','5 Austin Road','Seaford',3198,'0400000041','za@zalford.com','2000-01-04','notapplied',2,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('stan','findlay','5 Walkers Road','Carrum',3197,'0400000042','sf@sfindlay.com','2000-01-05','notapplied',3,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('reuben','ramirez','5 York Street','Mornington',3931,'0400000043','rr@rramirez.com','2000-01-06','notapplied',4,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('nyah','villegas','5 Walkers Road','Mt Eliza',3930,'0400000044','nv@nvillegas.com','2000-01-07','notapplied',5,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('ahmet','wormald','5 Clarendon Street','Thornbury',3071,'0400000045','aw@awormald.com','2000-01-08','notapplied',1,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('ruairi','powers','5 Cheddar Road','Reservoir',3073,'0400000046','rp@rpowers.com','2000-01-09','notapplied',2,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('glen','warner','5 The Blvd','Thomastown',3074,'0400000047','gw@gwarner.com','2000-01-10','notapplied',3,'A',1,0,0,0,'FALSE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('simon','vaughn','5 Oherns Road','Epping',3076,'0400000048','sv@svaughn.com','2000-01-11','notapplied',4,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('mahi','collins','6 Bitburg Street','Jacana',3047,'0400000049','mc@mcollins.com','2000-01-12','notapplied',5,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('ameera','kennedy','6 Playne Street','Frankston',3199,'0400000050','ak@akennedy.com','2000-01-13','notapplied',1,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('ifan','allen','6 Austin Road','Seaford',3198,'0400000051','ia@iallen.com','2000-01-14','notapplied',2,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('akram','winters','6 Walkers Road','Carrum',3197,'0400000052','aw@awinters.com','2008-01-01','notapplied',3,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('joanna','rahman','6 York Street','Mornington',3931,'0400000053','jr@jrahman.com','2012-01-02','notapplied',4,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('justin','peralta','6 Walkers Road','Mt Eliza',3930,'0400000054','jp@jperalta.com','2009-01-03','notapplied',5,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('kris','nicholson','6 Clarendon Street','Thornbury',3071,'0400000055','kn@knicholson.com','2000-01-18','notapplied',1,'A',1,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('caelan','churchill','6 Cheddar Road','Reservoir',3073,'0400000056','cc@cchurchill.com','2000-01-19','notapplied',2,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('rares','salgado','6 The Blvd','Thomastown',3074,'0400000057','rs@rsalgado.com','2000-01-01','notapplied',3,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('sohail','hayes','6 Oherns Road','Epping',3076,'0400000058','sh@shayes.com','2000-01-02','notapplied',4,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('farah','hyde','6 Bitburg Street','Jacana',3047,'0400000059','fh@fhyde.com','2000-01-03','notapplied',5,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('waseem','pritchard','7 Playne Street','Frankston',3199,'0400000060','wp@wpritchard.com','2000-01-04','notapplied',1,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('soren','zavala','7 Austin Road','Seaford',3198,'0400000061','sz@szavala.com','2000-01-05','notapplied',2,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('alessandra','todd','7 Walkers Road','Carrum',3197,'0400000062','at@atodd.com','2000-01-06','notapplied',3,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('alana','daniels','7 York Street','Mornington',3931,'0400000063','ad@adaniels.com','2000-01-07','notapplied',4,'A',1,0,0,0,'FALSE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('aiden','holman','7 Walkers Road','Mt Eliza',3930,'0400000064','ah@aholman.com','2000-01-08','notapplied',5,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('woodrow','kaiser','7 Clarendon Street','Thornbury',3071,'0400000065','wk@wkaiser.com','2000-01-09','notapplied',1,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('elli','travis','7 Cheddar Road','Reservoir',3073,'0400000066','et@etravis.com','2000-01-10','notapplied',2,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('zacharias','pate','7 The Blvd','Thomastown',3074,'0400000067','zp@zpate.com','2000-01-11','notapplied',3,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('tyrell','morrow','7 Oherns Road','Epping',3076,'0400000068','tm@tmorrow.com','2000-01-12','notapplied',4,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('gabriella','whitney','7 Bitburg Street','Jacana',3047,'0400000069','gw@gwhitney.com','2000-01-13','notapplied',5,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('talhah','mustafa','8 Playne Street','Frankston',3199,'0400000070','tm@tmustafa.com','2000-01-14','notapplied',1,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('uma','pennington','8 Austin Road','Seaford',3198,'0400000071','up@upennington.com','2008-01-01','notapplied',2,'A',1,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('tahmid','enriquez','8 Walkers Road','Carrum',3197,'0400000072','te@tenriquez.com','2012-01-02','notapplied',3,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('shanon','watt','8 York Street','Mornington',3931,'0400000073','sw@swatt.com','2009-01-03','notapplied',4,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('amelia-grace','odling','8 Walkers Road','Mt Eliza',3930,'0400000074','ao@aodling.com','2000-01-18','notapplied',5,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('lee','hahn','8 Clarendon Street','Thornbury',3071,'0400000075','lh@lhahn.com','2000-01-19','notapplied',1,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('alix','cleveland','8 Cheddar Road','Reservoir',3073,'0400000076','ac@acleveland.com','2000-01-01','notapplied',2,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('harold','fisher','8 The Blvd','Thomastown',3074,'0400000077','hf@hfisher.com','2000-01-02','notapplied',3,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('orson','king','8 Oherns Road','Epping',3076,'0400000078','ok@oking.com','2000-01-03','notapplied',4,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('fahad','woodard','8 Bitburg Street','Jacana',3047,'0400000079','fw@fwoodard.com','2000-01-04','notapplied',5,'A',1,0,0,0,'FALSE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('harper','head','9 Playne Street','Frankston',3199,'0400000080','hh@hhead.com','2000-01-05','notapplied',1,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('jadine','wilde','9 Austin Road','Seaford',3198,'0400000081','jw@jwilde.com','2000-01-06','notapplied',2,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('menna','daniel','9 Walkers Road','Carrum',3197,'0400000082','md@mdaniel.com','2000-01-07','notapplied',3,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('jak','wade','9 York Street','Mornington',3931,'0400000083','jw@jwade.com','2000-01-08','notapplied',4,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('khaleesi','frost','9 Walkers Road','Mt Eliza',3930,'0400000084','kf@kfrost.com','2000-01-09','notapplied',5,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('summer-rose','england','9 Clarendon Street','Thornbury',3071,'0400000085','se@sengland.com','2000-01-10','notapplied',1,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('junayd','traynor','9 Cheddar Road','Reservoir',3073,'0400000086','jt@jtraynor.com','2000-01-11','notapplied',2,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('kaitlin','iles','9 The Blvd','Thomastown',3074,'0400000087','ki@kiles.com','2000-01-12','notapplied',3,'A',1,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('malaika','house','9 Oherns Road','Epping',3076,'0400000088','mh@mhouse.com','2000-01-13','notapplied',4,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('laurence','hanson','9 Bitburg Street','Jacana',3047,'0400000089','lh@lhanson.com','2000-01-14','notapplied',5,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('tarik','rivera','10 Playne Street','Frankston',3199,'0400000090','tr@trivera.com','2008-01-01','notapplied',1,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('hailie','wall','10 Austin Road','Seaford',3198,'0400000091','hw@hwall.com','2012-01-02','notapplied',2,'A',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('gary','tomlinson','10 Walkers Road','Carrum',3197,'0400000092','gt@gtomlinson.com','2009-01-03','notapplied',3,'S',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('ryley','le','10 York Street','Mornington',3931,'0400000093','rl@rle.com','2000-01-18','notapplied',4,'M',0,0,0,0,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('mustafa','jaramillo','10 Walkers Road','Mt Eliza',3930,'0400000094','mj@mjaramillo.com','2000-01-19','notapplied',5,'L',0,2,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('ema','jensen','10 Clarendon Street','Thornbury',3071,'0400000095','ej@ejensen.com','2000-01-01','notapplied',1,'A',1,0,0,0,'FALSE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('janice','randall','10 Cheddar Road','Reservoir',3073,'0400000096','jr@jrandall.com','2000-01-02','notapplied',2,'S',0,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('yunus','norman','10 The Blvd','Thomastown',3074,'0400000097','yn@ynorman.com','2000-01-03','notapplied',3,'M',1,2,3,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('zaynah','greenaway','10 Oherns Road','Epping',3076,'0400000098','zg@zgreenaway.com','2000-01-04','notapplied',4,'L',1,0,0,4,'TRUE');
insert into walkers (walker_firstname, walker_lastname, walker_street_address, walker_town, walker_postcode, walker_mobile, walker_email, walker_dob,walker_licence_photo,  walker_overall_rating, walker_dog_size_preference, walker_30WO,walker_60WO, walker_30HV,walker_60HV, walker_active_membership) VALUES ('nakita','massey','10 Bitburg Street','Jacana',3047,'0400000099','nm@nmassey.com','2000-01-05','notapplied',5,'A',1,2,3,4,'TRUE');



-- create the bookings
CREATE TABLE bookings (
    booking_date DATE NOT NULL,
    booking_start_time BIGINT NOT NULL,
    booking_end_time BIGINT NOT NULL,
    booking_duration INTEGER NOT NULL,
    booking_photo_proof VARCHAR(100),
    booking_gps_image VARCHAR(100),
    booking_service_fee NUMERIC(8,2) NOT NULL,
    booking_our_comission NUMERIC(8,2) NOT NULL,
    booking_cancelled BOOLEAN DEFAULT FALSE,
    booking_whom_cancelled VARCHAR(20),
    booking_status VARCHAR(1),
    service_id INTEGER,
    FOREIGN KEY (service_id) REFERENCES services(service_id),
    dog_id INTEGER,
    FOREIGN KEY (dog_id) REFERENCES dogs(dog_id),
    owner_id INTEGER,
    FOREIGN KEY (owner_id) REFERENCES owners(owner_id),
    walker_id INTEGER,
    FOREIGN KEY (walker_id) REFERENCES walkers(walker_id) 
);





-- BOOKIGNS DATA
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627030800','1627032600',1800,'blank','blank',25,2.5,'FALSE','na','O',1,1,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627032600','1627034400',1800,'blank','blank',40,4,'FALSE','na','O',2,1,2,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627034400','1627036200',1800,'blank','blank',20,2,'FALSE','na','O',3,1,3,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627036200','1627038000',1800,'blank','blank',35,3.5,'FALSE','na','A',4,2,4,4);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627038000','1627039800',1800,'blank','blank',25,2.5,'FALSE','na','A',1,3,5,5);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627039800','1627041600',1800,'blank','blank',40,4,'FALSE','na','A',2,4,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627041600','1627043400',1800,'blank','blank',20,2,'FALSE','na','F',3,2,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627043400','1627045200',1800,'blank','blank',35,3.5,'FALSE','na','F',4,3,3,3);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627045200','1627047000',1800,'blank','blank',25,2.5,'FALSE','na','F',1,4,4,4);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627047000','1627048800',1800,'blank','blank',40,4,'FALSE','na','F',2,2,5,5);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627048800','1627052400',3600,'blank','blank',20,2,'FALSE','na','F',3,3,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627052400','1627056000',3600,'blank','blank',35,3.5,'FALSE','na','F',4,4,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627056000','1627059600',3600,'blank','blank',25,2.5,'TRUE','1','C',1,2,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-23','1627059600','1627063200',3600,'blank','blank',40,4,'TRUE','2','C',2,3,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627117200','1627119000',1800,'blank','blank',25,2.5,'FALSE','na','O',1,1,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627119000','1627120800',1800,'blank','blank',40,4,'FALSE','na','O',2,1,2,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627120800','1627122600',1800,'blank','blank',20,2,'FALSE','na','O',3,1,3,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627122600','1627124400',1800,'blank','blank',35,3.5,'FALSE','na','A',4,2,4,4);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627124400','1627126200',1800,'blank','blank',25,2.5,'FALSE','na','A',1,3,5,5);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627126200','1627128000',1800,'blank','blank',40,4,'FALSE','na','A',2,4,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627128000','1627129800',1800,'blank','blank',20,2,'FALSE','na','F',3,2,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627129800','1627131600',1800,'blank','blank',35,3.5,'FALSE','na','F',4,3,3,3);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627131600','1627133400',1800,'blank','blank',25,2.5,'FALSE','na','F',1,4,4,4);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627133400','1627135200',1800,'blank','blank',40,4,'FALSE','na','F',2,2,5,5);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627135200','1627138800',3600,'blank','blank',20,2,'FALSE','na','F',3,3,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627138800','1627142400',3600,'blank','blank',35,3.5,'FALSE','na','F',4,4,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627142400','1627146000',3600,'blank','blank',25,2.5,'TRUE','1','C',1,2,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-24','1627146000','1627149600',3600,'blank','blank',40,4,'TRUE','2','C',2,3,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627203600','1627205400',1800,'blank','blank',25,2.5,'FALSE','na','O',1,1,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627205400','1627207200',1800,'blank','blank',40,4,'FALSE','na','O',2,1,2,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627207200','1627209000',1800,'blank','blank',20,2,'FALSE','na','O',3,1,3,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627209000','1627210800',1800,'blank','blank',35,3.5,'FALSE','na','A',4,2,4,4);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627210800','1627212600',1800,'blank','blank',25,2.5,'FALSE','na','A',1,3,5,5);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627212600','1627214400',1800,'blank','blank',40,4,'FALSE','na','A',2,4,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627214400','1627216200',1800,'blank','blank',20,2,'FALSE','na','F',3,2,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627216200','1627218000',1800,'blank','blank',35,3.5,'FALSE','na','F',4,3,3,3);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627218000','1627219800',1800,'blank','blank',25,2.5,'FALSE','na','F',1,4,4,4);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627219800','1627221600',1800,'blank','blank',40,4,'FALSE','na','F',2,2,5,5);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627221600','1627225200',3600,'blank','blank',20,2,'FALSE','na','F',3,3,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627225200','1627228800',3600,'blank','blank',35,3.5,'FALSE','na','F',4,4,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627228800','1627232400',3600,'blank','blank',25,2.5,'TRUE','1','C',1,2,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-25','1627232400','1627236000',3600,'blank','blank',40,4,'TRUE','2','C',2,3,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627290000','1627291800',1800,'blank','blank',25,2.5,'FALSE','na','O',1,1,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627291800','1627293600',1800,'blank','blank',40,4,'FALSE','na','O',2,1,2,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627293600','1627295400',1800,'blank','blank',20,2,'FALSE','na','O',3,1,3,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627295400','1627297200',1800,'blank','blank',35,3.5,'FALSE','na','A',4,2,4,4);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627297200','1627299000',1800,'blank','blank',25,2.5,'FALSE','na','A',1,3,5,5);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627299000','1627300800',1800,'blank','blank',40,4,'FALSE','na','A',2,4,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627300800','1627302600',1800,'blank','blank',20,2,'FALSE','na','F',3,2,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627302600','1627304400',1800,'blank','blank',35,3.5,'FALSE','na','F',4,3,3,3);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627304400','1627306200',1800,'blank','blank',25,2.5,'FALSE','na','F',1,4,4,4);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627306200','1627308000',1800,'blank','blank',40,4,'FALSE','na','F',2,2,5,5);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627308000','1627311600',3600,'blank','blank',20,2,'FALSE','na','F',3,3,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627311600','1627315200',3600,'blank','blank',35,3.5,'FALSE','na','F',4,4,2,2);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627315200','1627318800',3600,'blank','blank',25,2.5,'TRUE','1','C',1,2,1,1);
INSERT INTO BOOKINGS (booking_date,booking_start_time,booking_end_time,booking_duration,booking_photo_proof,booking_gps_image,booking_service_fee,booking_our_comission,booking_cancelled,booking_whom_cancelled,booking_status,service_id,dog_id,owner_id,walker_id) VALUES ('2021-07-26','1627318800','1627322400',3600,'blank','blank',40,4,'TRUE','2','C',2,3,2,2);